Docs: add more delta updates info and rockset-specific caveats
estuary/flow pull request #399
Opened 2022-03-04 19:42 UTC by oliviamiannone

**Description:**

In light of https://github.com/estuary/connectors/issues/115, the Rockset connector can handle TOASTed values without issue, but there are important considerations regarding delta updates and reduction strategies that users should be aware of.

**Documentation links affected:**
na

**Notes for reviewers:**

The usual - needs a fact-check as some assumptions were involved. One specific question noted inline.

2022-03-04 23:10 UTC, psFried requested changes
I think this helps a lot. I gave a suggestion for `FOR REVIEW` paragraph, but everything else looks great

2022-03-04 23:10 UTC, psFried commented on site/docs/reference/Connectors/materialization-connectors/Rockset.md
> +This means that Rockset merges documents by key when they arrive, using semantics that are somewhat different than Flow's.
Here's my take on this:

> Rockset will merge documents having the same key, as defined by the Flow collection. The documents will be merged according to semantics of [RFC 7396 - JSON merge](https://datatracker.ietf.org/doc/html/rfc7396). This is different from how Flow reduces documents, and Rockset's merge will _not_ use any reduction annotations from your Flow schema. If your Flow JSON schema has a top-level `merge` reduction strategy and all other fields have the default reduction strategy of `lastWriteWins`, then the results will be equivalent. If your Flow collection's JSON schema uses any other reduction stategies, then the view that's materialized to Rockset will differ from the view of the same collection that's materialized to an RDBMS such as Postgres.

2022-03-04 23:10 UTC, psFried commented on site/docs/reference/Connectors/materialization-connectors/Rockset.md
> +In most cases, this difference won't affect your data. However, using certain
> In most cases, this difference won't affect your data

This isn't going to age well, as I expect that reduction annotations will become much more commonly used than they are now. I'm a little torn about whether to leave it for now, but just FYI

2022-03-05 00:31 UTC, willdonnelly commented on site/docs/reference/Connectors/materialization-connectors/Rockset.md
> +This means that Rockset merges documents by key when they arrive, using semantics that are somewhat different than Flow's.
s/will differ/may differ/ perhaps?

2022-03-07 18:38 UTC, merged